export const UPDATE_MESSAGE = 'UPDATE_MESSAGE';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const FETCH_MESSAGES = 'FETCH_MESSAGES';

export const UPDATE_CHANNEL = "UPDATE_CHANNEL";

export const UPDATE_USER = "UPDATE_USER";